version: '3.9'

services:

  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bankdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
